apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: crudpro-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: crudpro   # 너의 Deployment 이름
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   # CPU 50% 넘으면 스케일 아웃